### ISSUE TITLE
Is this repo still being maintained ?

### ISSUE THREAD

**Issue by mithunmanohar** [FreckleIOT/ecs-airflow#5]
Excellent template for deploying Airflow in ECS. How ever I do not see any activities in the repo recently. Is this repo still relevant/ being maintained? If not could you point me to any similar actively maintained repo.

**Comment by calvinlfer** [comment]
Hey there, both @hackmad and I have moved on and don’t have the time to maintain this. The principles are largely the same so doing an upgrade is not too bad. There is also https://github.com/rolanddb/airflow-on-kubernetes
